// Generates ipad.html from index.html — the SAME app, retargeted for iPad/tablet.
// No feature changes: index.html is copied verbatim and a tablet CSS layer is
// appended after the main <style> block. Re-run after any index.html update:
//   node make-ipad.mjs
import fs from "fs";

let s = fs.readFileSync("index.html", "utf8");

// 1) Own title for the tablet build
s = s.replace(
  "<title>AgileRx — Home Screen Prototype</title>",
  "<title>AgileRx for iPad</title>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
);

// 2) Tablet override layer — inserted right after the main style block so it
//    wins the cascade without touching any original rule.
const TABLET = `
<style id="tablet-overrides">
  /* ===== iPad / tablet build (generated by make-ipad.mjs) =====
     The phone bezel becomes a full-height tablet canvas: the app column is
     centred at a comfortable tablet width, chrome-only pieces (mock bezel,
     dynamic island, backdrop heading) are hidden, and the floating layers
     (CTA, sheet, nav) are capped so phone-designed blocks don't over-stretch.
     Everything inside the app is untouched. */
  /* Side areas match the app's own ground so landscape reads as one screen,
     not a letterboxed phone (the app UI is light-only by design). */
  body { display: block; padding: 0; gap: 0; min-height: 100dvh; background: #F6F5FA; }
  .stage-head { display: none; }
  .phone {
    width: min(760px, 100vw);
    margin: 0 auto;
    padding: 0;
    border-radius: 0;
    box-shadow: none;
    background: transparent;
  }
  .screen {
    height: 100dvh;
    min-height: 100dvh;
    border-radius: 0;
  }
  .island { display: none; } /* iPhone chrome — the status bar itself stays (iPad-style: time left, battery right) */

  /* Floating layers keep phone-scale widths, centred on the wider canvas */
  .next-fixed { left: max(20px, calc(50% - 280px)); right: max(20px, calc(50% - 280px)); }
  .sheet { left: max(0px, calc(50% - 300px)); right: max(0px, calc(50% - 300px)); }
  .float-nav { left: max(14px, calc(50% - 330px)); right: max(14px, calc(50% - 330px)); }

  /* Pre-app overlays (Sign in / setup / lock): centre the form column */
  .pre { padding-left: max(28px, calc(50% - 250px)); padding-right: max(28px, calc(50% - 250px)); }
</style>`;

const mark = "</style>";
const i = s.indexOf(mark);
if (i < 0) throw new Error("main </style> not found");
s = s.slice(0, i + mark.length) + TABLET + s.slice(i + mark.length);

fs.writeFileSync("ipad.html", s);
console.log("ipad.html generated (" + Math.round(s.length / 1024) + " KB)");
